app = "kabootar"
primary_region = "bom"

[build]

[[services]]
  internal_port = 18937
  protocol = "udp"
  [[services.ports]]
    port = 18937

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "2s"
    path = "/rt/v1/ping"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
